---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Write success to file
      copy:
        content: "success\n"
        dest: /tmp/ansible_output.txt

    - name: Print file content
      shell: cat /tmp/ansible_output.txt
      register: file_content
      when: not ansible_check_mode

    - name: Show result
      debug:
        msg: "{{ file_content.stdout | default('check mode - not executed') }}"

    - name: Push output to job artifacts
      set_stats:
        data:
          file_content: "{{ file_content.stdout | default('check mode - not executed') }}"
          hostname: "{{ inventory_hostname }}"
